<?xml version="1.0" encoding="utf-8"?><Database Name="H5projekt" Class="DataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=h5projekt.database.windows.net;Initial Catalog=H5projekt;User ID=h5pAdmin" SettingsObjectName="H5pro.Properties.Settings" SettingsPropertyName="H5projektConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Salt" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MCID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Message" Member="Messages" ThisKey="UserID" OtherKey="FromUser" Type="Message" />
      <Association Name="User_Message1" Member="Messages1" ThisKey="UserID" OtherKey="ToUser" Type="Message" />
      <Association Name="MatchCriteria_User" Member="MatchCriteria" ThisKey="MCID" OtherKey="MCID" Type="MatchCriteria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Shows" Member="Shows">
    <Type Name="Show">
      <Column Name="ShowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Genre" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Show_MCShowRelation" Member="MCShowRelations" ThisKey="ShowID" OtherKey="ShowID" Type="MCShowRelation" />
    </Type>
  </Table>
  <Table Name="dbo.Messages" Member="Messages">
    <Type Name="Message">
      <Column Name="MessageID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ToUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FromUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sub" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TextMessage" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="User_Message" Member="User" ThisKey="FromUser" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="User_Message1" Member="User1" ThisKey="ToUser" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MCShowRelation" Member="MCShowRelations">
    <Type Name="MCShowRelation">
      <Column Name="MCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShowID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Show_MCShowRelation" Member="Show" ThisKey="ShowID" OtherKey="ShowID" Type="Show" IsForeignKey="true" />
      <Association Name="MatchCriteria_MCShowRelation" Member="MatchCriteria" ThisKey="MCID" OtherKey="MCID" Type="MatchCriteria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MatchCriteria" Member="MatchCriterias">
    <Type Name="MatchCriteria">
      <Column Name="MCID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Commitment" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StreamingServices" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="MatchCriteria_User" Member="Users" ThisKey="MCID" OtherKey="MCID" Type="User" />
      <Association Name="MatchCriteria_MCShowRelation" Member="MCShowRelations" ThisKey="MCID" OtherKey="MCID" Type="MCShowRelation" />
    </Type>
  </Table>
</Database>